# Generated by Django 5.2.3 on 2025-07-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
