# Generated by Django 5.2.3 on 2025-07-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('visit_reason', models.CharField(max_length=100)),
                ('health_condition', models.CharField(choices=[('Critical', 'Critical'), ('Serious', 'Serious'), ('Stable', 'Stable'), ('Recovered', 'Recovered'), ('Deceased', 'Deceased'), ('Normal', 'Normal')], default='Normal', max_length=50)),
                ('treatment_given', models.TextField(blank=True, null=True)),
                ('parent_contacted', models.BooleanField(default=False)),
                ('referred_to_doctor', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_records', to='nurse.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_records', to='student.studentprofile')),
            ],
        ),
    ]
