# Generated by Django 5.2.3 on 2025-06-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
    ]
