# Generated by Django 5.2.3 on 2025-06-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_book_created_at'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='student.class'),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='student.section'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
