# Generated by Django 5.2.3 on 2025-06-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_bookissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('book_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='lms.bookissue')),
            ],
        ),
    ]
