# Generated by Django 5.2.3 on 2025-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_bookreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='has_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
