# Generated by Django 5.2.3 on 2025-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_bookissue_has_returned_bookreturn_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreturn',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
