# Generated by Django 5.2.3 on 2025-07-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(blank=True, null=True, upload_to='notices/%Y/%m/%d/')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Info', 'Info')], default='Normal', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
