# Generated by Django 5.2.3 on 2025-06-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student'), ('librarian', 'Librarian'), ('attender', 'Attender'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('health_staff', 'Health Staff'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
